language: rust
rust: nightly
sudo: required
dist: xenial
services: docker

matrix:
  include:
   - env: TARGET=arm-linux-androideabi

install: travis_retry rustup target add $TARGET

script:
  - cargo generate-lockfile --manifest-path libc-test/Cargo.toml
  - if [[ $TRAVIS_OS_NAME = "linux" ]] && [[ $BUILD_ONLY != "1" ]]; then
      sh ci/run-docker.sh $TARGET;
    else
      sh ci/run.sh $TARGET;
    fi
env:
  global:
    secure: "e2/3QjgRN9atOuSHp22TrYG7QVKcYUWY48Hi9b60w+r1+BhPkTseIJLte7WefRhdXtqpjjUJTooKDhnurFOeHaCT+nmBgiv+FPU893sBl4bhesY4m0vgUJVbNZcs6lTImYekWVb+aqjGdgV/XAgCw7c3kPmrZV0MzGDWL64Xaps="

notifications:
  email:
    on_success: never
