variables:
  - group: secrets
resources:
  repositories:
    - repository: rustinfra
      type: github
      name: rust-lang/simpleinfra
      endpoint: gnzlbg
trigger: ["auto-libc","try"]
pr: ["master"]

jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: azure-install-rust.yml
      - bash: cargo run
        displayName: Execute run.sh
    strategy:
      matrix:
        x86_64-pc-windows-gnu:
          TARGET: x86_64-pc-windows-gnu
          ARCH_BITS: 64
          ARCH: x86_64
        x86_64-pc-windows-msvc:
          TARGET: x86_64-pc-windows-msvc
        i686-pc-windows-gnu:
          TARGET: i686-pc-windows-gnu
          ARCH_BITS: 32
          ARCH: i686
        i686-pc-windows-msvc:
          TARGET: i686-pc-windows-msvc
